version: '3.8'

services:
  mongo:
    image: mongo
    hostname: mongo.devlumen.net
    container_name: lm-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      test_net:
        ipv4_address: 192.168.4.12

  mongo-express:
    image: mongo-express
    hostname: mongo-express.devlumen.net
    container_name: lm-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      test_net:
        ipv4_address: 192.168.4.11

  api:
    depends_on:
    - mongo 
    hostname: api.devlumen.net
    container_name: lm-api 
    build:
      context: .
      dockerfile: ./container/Dockerfile.api
      args:
          # Available [trace|debug|profile]. Use Comma separated available values for multiple mode
          # Use "off" to disable xdebug
          #- XDEBUG_MODES=debug,trace
          - XDEBUG_MODES=debug,trace
          # Set the following values to overwrite the existing settings.
          # Uncomment the following line and change value.
          - REMOTE_HOST=host.docker.internal # Host machine IP
          - REMOTE_PORT=9000 # IDE/Editor's listener port
          - IDE_KEY=docker # IDE's filter/listener key      
    networks:
      test_net:
        ipv4_address: 192.168.4.10
    ports:
      - 8000:8000
      - 9003:9003
    volumes:
      - ./lumen-app/:/var/www/html/
      - /var/www/html/vendor/
      # Xdebug Log files will be written in this directory
      - ./container/logs/xdebug:/tmp/xdebug      
    restart: always

networks:
  test_net:
    name: test_net
    external: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.1
